#!/bin/bash
case "$(uname -s)" in
  Linux*)
    IP=$(ip addr | grep inet | grep -v inet6 | awk '{print $2}' | awk -F '/' '{print $1}' | grep -v '127.0.0.1')
    ;;
  MINGW*)
    IP=$(ipconfig | grep IPv4 | awk '{print $NF}' | head -n 1)
    ;;
  CYGWIN*)
    IP=$(ipconfig | grep IPv4 | awk '{print $NF}' | head -n 1)
    ;;
  *)
    echo &>2 "Error: Unknown platform."
    exit 1
    ;;
esac
hash erl 2>/dev/null
if [ $? != 0 ]; then
  echo >&2 "erl not in PATH, try to find it"
  erl=$(echo $PWD/../erl*/)
  if [ -f "$erl/bin/erl.exe" ]; then
    pwd=$PWD
    cd "$erl"
    echo "found $erl/bin/erl.exe"
    ./Install.exe -s
    export PATH="$erl/bin:$PATH"
    erlc 2>/dev/null
    if [ $? != 0 ]; then
      echo >&2 "seems missing dependency, installing vcredist_x64"
      ./vcredist_x64.exe
      cd "$pwd"
      $0 $@
      exit $?
    fi
    cd "$pwd"
  else
    echo >&2 "erl runtime not found, exiting"
    exit 1
  fi
fi
if [ "$MODE" == "master" ]; then
  name="master@$IP"
else
  name="worker@$IP"
fi
#find _rel -name vm.args -exec sed -i "s/^-name .*\$/-name $name/" {} \;
#./rel.sh console
find rel -name vm.args -exec sed -i "s/^-name .*\$/-name $name/" {} \;
./dev-otp
